name: CI

on:
  push:
    branches:
         - main

jobs:
  build:
    runs-on: ubutnu-latest

    steps:
      - name: Get your code
        uses: actions/checkout@v2

      - name: Say Hello to the World
        run: echo "Hello, Krizznaa"

